---
- name: install haproxy on debian
  when: ansible_facts.os_family | lower == 'debian'
  shell: |
    apt update
    apt install -y haproxy

- name: install haproxy on redhat
  when: ansible_facts.os_family | lower == 'redhat'
  shell: |
    dnf update -y
    dnf install -y haproxy

- name: copy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    backup: yes
    force: yes

- name: Start haproxy
  shell: |
    systemctl restart haproxy
